if [ ! -n "$ZSH" ]; then
  ZSH=$HOME/.zsh
fi

export ELLIPSIS_PROTO=ssh

source $ZSH/antigen.zsh

export VISUAL=nvim
export EDITOR="$VISUAL"
DEFAULT_USER=tbjers

export PROJECTS=$HOME/git
export GOPATH=$HOME/go

PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH
PATH="$HOME/.rbenv/bin:$HOME/.packer/bin:$HOME/.composer/vendor/bin:$PATH:$GOPATH/bin"

# Source Ellipsis init code or fallback to the older system
if [ -f ~/.ellipsis/init.sh ]; then
	. ~/.ellipsis/init.sh
else
	export PATH=$PATH:~/.ellipsis/bin
fi

POSTGRES_PATH=/Applications/Postgres.app/Contents/Versions/latest/bin
[ -d "$POSTGRES_PATH" ] && PATH="$POSTGRES_PATH:$PATH"

ANDROID_NDK_PATH=$HOME/Library/Android/ndk
ANDROID_SDK_PATH=$HOME/Library/Android/sdk/platform-tools
[ -d "$ANDROID_NDK_PATH" ] && PATH="$ANDROID_NDK_PATH:$PATH"
[ -d "$ANDROID_SDK_PATH" ] && PATH="$ANDROID_SDK_PATH:$PATH"

export NVM_DIR="$HOME/.nvm"
PATH=$NVM_DIR/versions/node/v6.9.1/bin:$PATH
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Source asdf
if [ -f ~/.asdf/asdf.sh ]; then
	. ~/.asdf/asdf.sh
fi

alias vim="stty stop '' -ixoff ; nvim"
alias be='bundle exec'

# kqueue is broken in OS X
export EVENT_NOKQUEUE=1

ttyctl -f

[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

# Use PHP provided by Homebrew
PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

[ -f "$HOME/.asdf/asdf.sh" ] && source "$HOME/.asdf/asdf.sh"
[ -f "$HOME/.asdf/completions/asdf.bash" ] && source "$HOME/.asdf/completions/asdf.bash"

export PATH

eval "$(rbenv init -)"
eval "$(direnv hook zsh)"

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  git
  git-flow
  git-extras
  github
  rbenv
  common-aliases
  zsh-users/zsh-syntax-highlighting
  tbjers/zsh-plugins plugins/cl
  ssh-agent
EOBUNDLES

antigen theme theunraveler

antigen apply

[ -f "$HOME/.iterm2_shell_integration.`basename $SHELL`" ] && source "$HOME/.iterm2_shell_integration.`basename $SHELL`"
[ -f "$HOME/.credentials.`basename $SHELL`" ] && source "$HOME/.credentials.`basename $SHELL`"

alias gf='git flow'
alias gs='git status'
alias nah='git reset --hard; git clean -df;'
alias dokku='$HOME/.dokku/contrib/dokku_client.sh'

export HOMEBREW_NO_ANALYTICS=1

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/tbjers/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/tbjers/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/tbjers/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/tbjers/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
