if [ ! -n "$ZSH" ]; then
  ZSH=$HOME/.zsh
fi

export ELLIPSIS_PROTO=ssh

source $ZSH/antigen.zsh

export VISUAL=vim
export EDITOR="$VISUAL"
DEFAULT_USER=tbjers

export PROJECTS=$HOME/git
export GOPATH=$HOME/go

PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH
PATH="$HOME/.rbenv/bin:$HOME/.packer/bin:$HOME/.composer/vendor/bin:$PATH:$GOPATH/bin"
PATH="$HOME/Applications/apache-maven-3.3.3/bin:$PATH"

export PATH

# Source Ellipsis init code or fallback to the older system
if [ -f ~/.ellipsis/init.sh ]; then
	. ~/.ellipsis/init.sh
else
	export PATH=$PATH:~/.ellipsis/bin
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

alias vim="stty stop '' -ixoff ; vim"
alias be='bundle exec'

ttyctl -f

eval "$(rbenv init -)"

[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  git
  composer
  bower
  git-flow
  git-extras
  github
  jake-node
  node
  npm
  nvm
  rbenv
  gem
  rake
  ruby
  common-aliases
  tbjers/zsh-plugins plugins/cl
  tbjers/zsh-plugins plugins/gibo
  ssh-agent
EOBUNDLES

antigen theme theunraveler

antigen apply

[ -f "$HOME/.credentials.`basename $SHELL`" ] && source "$HOME/.credentials.`basename $SHELL`"

alias git='hub'
alias gf='git flow'
alias mvn-clean-install='GIT_COMMIT=`` mvn clean install --update-snapshots --define maven.test.skip=true'
if type 'gnome-open' > /dev/null; then
  alias open='gnome-open'
fi
