if [ ! -n "$ZSH" ]; then
  ZSH=$HOME/.zsh
fi

export ELLIPSIS_PROTO=ssh

source $ZSH/antigen.zsh

export VISUAL=vim
export EDITOR="$VISUAL"
DEFAULT_USER=tbjers

export PROJECTS=$HOME/git
export GOPATH=$HOME/go

PATH=/usr/local/bin:/usr/local/sbin:$HOME/bin:$PATH
PATH="$HOME/.rbenv/bin:$HOME/.packer/bin:$HOME/.composer/vendor/bin:$PATH:$GOPATH/bin"
PATH="$HOME/Applications/apache-maven-3.3.3/bin:$PATH"

export PATH

# Source Ellipsis init code or fallback to the older system
if [ -f ~/.ellipsis/init.sh ]; then
	. ~/.ellipsis/init.sh
else
	export PATH=$PATH:~/.ellipsis/bin
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

alias vim="stty stop '' -ixoff ; vim"
alias be='bundle exec'

ttyctl -f

if which rbenv > /dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

if which antigen > /dev/null 2>&1; then
  antigen use oh-my-zsh

  antigen bundles <<EOBUNDLES
    git
    composer
    bower
    git-flow
    git-extras
    github
    common-aliases
    tbjers/zsh-plugins plugins/cl
    tbjers/zsh-plugins plugins/gibo
    ssh-agent
EOBUNDLES

  if which rbenv > /dev/null 2>&1; then
    antigen bundles <<EOBUNDLES
      rbenv
      gem
      rake
      ruby
EOBUNDLES
  fi

  if which nvm > /dev/null 2>&1; then
    antigen bundles <<EOBUNDLES
      jake-node
      node
      npm
      nvm
EOBUNDLES
  fi

  antigen theme theunraveler

  antigen apply
else
  echo "WARNING: Antigen is not installed. Please rerun:"
  echo "$ ellipsis install tbjers/dot-zsh"
fi

[ -f "$HOME/.credentials.`basename $SHELL`" ] && source "$HOME/.credentials.`basename $SHELL`"

alias git='hub'
alias gf='git flow'
alias gs='git status'
alias nah='git reset --hard; git clean -df;'
alias mvn-clean-install='GIT_COMMIT=`` mvn clean install --update-snapshots --define maven.test.skip=true'
if type 'gnome-open' > /dev/null; then
  alias open='gnome-open'
fi
